hw7
YaroslavGlonin/kiparo_course pull request #1
Opened 2023-05-02 03:56 UTC by YaroslavGlonin

hw7

2023-05-03 09:30 UTC, pvd-teacher requested changes

2023-05-03 09:30 UTC, pvd-teacher commented on .idea/gradle.xml
.idea не должно быть в репозитории, нужно добавить в .gitignore

2023-05-03 09:30 UTC, pvd-teacher commented on app/src/main/java/com/kiparo/hw7/WorkManager/JokeUpdateWorker.kt
> +                if (Di.isInternetConnected()) {
настраивается через Constraints как вы и сделали - поэтому можно удалить весь код связанный с проверкой сети

2023-05-03 09:30 UTC, pvd-teacher commented on app/src/main/java/com/kiparo/hw7/broadcastreceiver/UpdateScheduleReceiver.kt
> +                println("BTCScheduler UpdateScheduleReceiver onReceive: ${intent?.action}")
))

2023-05-03 09:30 UTC, pvd-teacher commented on app/src/main/java/com/kiparo/hw7/storage/Storage.kt
> +   private val model: ModelCategoriesPeriod = ModelCategoriesPeriod(1,"s")
А кто это? )) Надо убрать

2023-05-03 09:30 UTC, pvd-teacher commented on app/src/main/java/com/kiparo/hw7/storage/repo/RatesRepository.kt
> +interface RatesRepository {
Все переименовываем под этот проект

2023-05-03 09:30 UTC, pvd-teacher commented on app/src/main/java/com/kiparo/hw7/storage/repo/RatesRepositoryImpl.kt
> +class RatesRepositoryImpl(
Переименовываем

2023-05-03 09:30 UTC, pvd-teacher commented on app/src/main/java/com/kiparo/hw7/ui/MainActivity.kt
> +    private val updateViewModel: UpdateViewModel by viewModels {
давайте используем одну вьюмодель в данном случае и переименуем методы ее в такие названия, которые не будут раскрывать детали реазизации

2023-05-03 12:52 UTC, YaroslavGlonin commented on app/src/main/java/com/kiparo/hw7/WorkManager/JokeUpdateWorker.kt
> +                if (Di.isInternetConnected()) {
убрал)

2023-05-04 11:43 UTC, YaroslavGlonin commented on app/src/main/java/com/kiparo/hw7/broadcastreceiver/RebootReceiver.kt
> +        CoroutineScope(Dispatchers.Default).launch{
Исправил

2023-05-04 11:45 UTC, YaroslavGlonin commented on app/src/main/java/com/kiparo/hw7/storage/repo/RatesRepository.kt
> +    suspend fun saveRatesToDb(model: ModelCategoriesPeriod)
Ок в будущем учту

2023-05-07 19:36 UTC, tim-teacher requested changes

2023-05-07 19:36 UTC, tim-teacher commented on app/src/main/java/com/kiparo/hw7/WorkManager/JokeUpdateWorker.kt
> +    private fun createNotification(joke: ModelCategoryData): Notification {
Хорошо бы вынести работу с нотификациями в отдельный класс

2023-05-07 19:36 UTC, tim-teacher commented on app/src/main/java/com/kiparo/hw7/broadcastreceiver/AlarmScheduler.kt
> +        Di.alarmScheduler
`Di` убираем из `AlarmScheduler`, сюда подаем время

2023-05-07 19:36 UTC, tim-teacher commented on app/src/main/java/com/kiparo/hw7/broadcastreceiver/RebootReceiver.kt
> +            println("BTCScheduler RebootReceiver onReceive: ${intent?.action}")
`BTCScheduler`

2023-05-07 19:36 UTC, tim-teacher commented on app/src/main/java/com/kiparo/hw7/broadcastreceiver/RebootReceiver.kt
> +         period = Di.ratesRepository.getFromDb()?.period ?: 15
Что такое `15`? :)

2023-05-07 19:36 UTC, tim-teacher commented on app/src/main/java/com/kiparo/hw7/broadcastreceiver/UpdateScheduleReceiver.kt
> +                println("BTCScheduler UpdateScheduleReceiver onReceive: ${intent?.action}")
Не поменяли, даже файл стоит неизмененным

2023-05-07 19:36 UTC, tim-teacher commented on app/src/main/java/com/kiparo/hw7/constant/Constant.kt
> +    const val BASE_URL = "https://api.chucknorris.io/"
Не исправлено

2023-05-07 19:36 UTC, tim-teacher commented on app/src/main/java/com/kiparo/hw7/data/ModelCategoriesPeriod.kt
> +}
скобки можно убрать

2023-05-07 19:36 UTC, tim-teacher commented on app/src/main/java/com/kiparo/hw7/data/ModelCategoryData.kt
> +)
Форматирование

2023-05-07 19:36 UTC, tim-teacher commented on app/src/main/java/com/kiparo/hw7/storage/Storage.kt
> +   private val model: ModelCategoriesPeriod = ModelCategoriesPeriod(1,"s")
Не исправлено

2023-05-07 19:36 UTC, tim-teacher commented on app/src/main/java/com/kiparo/hw7/storage/Storage.kt
> +    suspend fun getRates(): ModelCategoriesPeriod? {
Не исправлено

2023-05-07 19:36 UTC, tim-teacher commented on app/src/main/java/com/kiparo/hw7/storage/Storage.kt
> +    suspend fun clearRates() {
Не исправлено

2023-05-07 19:36 UTC, tim-teacher commented on app/src/main/java/com/kiparo/hw7/storage/repo/RatesRepository.kt
> +interface RatesRepository {
Не исправлено

2023-05-07 19:36 UTC, tim-teacher commented on app/src/main/java/com/kiparo/hw7/storage/repo/RatesRepository.kt
> +    suspend fun saveRatesToDb(model: ModelCategoriesPeriod)
Не в будущем, а тут), когда мы даем заметки мы всегда помечаем, что можно не исправлять в этом проекте. 
Это достаточно грубая ошибка, поэтому согласен с Павлом

2023-05-07 19:36 UTC, tim-teacher commented on app/src/main/java/com/kiparo/hw7/storage/repo/RatesRepositoryImpl.kt
> +class RatesRepositoryImpl(
Не исправлено

2023-05-14 07:00 UTC, merged